### ISSUE TITLE
[dev]ステージング環境の準備

### ISSUE THREAD

**Issue by MikuroXina** [approvers/site#173]
デプロイされる前にサイトのステージング環境を用意して動作確認できるようにしたいです. 現在は `main` ブランチに直接マージしてそのタイミングでデプロイしています.

作業途中を `staging` ブランチにマージするようにして, その内容を別途ステージング環境へデプロイして確認できるようにすることが理想です.

以下でステージング環境を用意する方法を検討しましょう.

**Comment by mirror-kt** [comment]
提案: デプロイ先をnetlifyなどに変える
staging機能を提供してるデプロイサーバーに切り替えることで実現できそうです。

**Comment by MikuroXina** [comment]
ステージングデプロイが無くても, 先にステージングブランチだけ作っておいてもいいかもしれませんね

**Comment by MikuroXina** [comment]
`staging` ブランチを追加しました

**Comment by MikuroXina** [comment]
現在の PR のベースを `staging` に変更しました

**Comment by MikuroXina** [comment]
`staging` から `main` へのマージをいつ行うのか決めておきたいです, 特に無いなら機能の区切りが良いところで `staging` から `main` への PR を作成します.

**Comment by siketyan** [comment]
Netlify は Org だと無料で 1 人までしか管理できず属人化しちゃうので CI をうまく使って /staging 以下に置くとかでよさそう
