### ISSUE TITLE
Cloudflare Pages への移行

### ISSUE THREAD

**Issue by MikuroXina** [approvers/site#182]
@siketyan からの提案です. 現在は GitHub Pages にデプロイしていますが, これを [Cloudflare Pages](https://pages.cloudflare.com/) へ移行するというものです.

プレビューデプロイ機能があるため, #173 にも関連します.

誰がいつまでに実施するか決めておきましょう.

**Comment by siketyan** [comment]
ついでに `approvers.dev.` を Cloudflare に移行して管理者を増やしたい（現状こるくくん待ちになっているので）

**Comment by siketyan** [comment]
手順
1. 限界開発鯖の CF アカウントを作る
2. `approvers.dev.` ゾーンを移行する？
3. CF Pages でデプロイしてみる（とりあえず `canary.approvers.dev` とかに）
4. 切り替え

**Comment by siketyan** [comment]
CF アカウント作ったりするのは @Colk-tech がいいかな？

**Comment by siketyan** [comment]
CF は AWS みたいにアカウントに複数の管理者を持てるので

**Comment by siketyan** [comment]
@Colk-tech Yep

![image](https://user-images.githubusercontent.com/12772118/114991667-cfb60500-9ed4-11eb-8864-7951387353e8.png)

**Comment by Colk-tech** [comment]
Oh, I see
Then how much does this cost

**Comment by mirror-kt** [comment]
DNSとpages使うだけなら金要らなそう

**Comment by siketyan** [comment]
Yep

**Comment by Colk-tech** [comment]
とりあえず今すぐゾーン移行する?

**Comment by siketyan** [comment]
まだ CF のアカウントを持っていないのですが

**Comment by Colk-tech** [comment]
私の方で作成しました

**Comment by siketyan** [comment]
@Colk-tech root@siketyan.dev をアカウントに追加してほしい

**Comment by Colk-tech** [comment]
> @Colk-tech [root@siketyan.dev](mailto:root@siketyan.dev) をアカウントに追加してほしい

*** DONE ***

**Comment by siketyan** [comment]
@Colk-tech こなーい　me@s6n.jp に送ってみて

**Comment by mirror-kt** [comment]
DNSの管理者誰に割り当てる問題一応ありそう
approvers.devゾーン触れるからなぁ

**Comment by siketyan** [comment]
まあ全員とまではしなくていいと思うけど数人はほしいね，特にレスポンスはやい民で

**Comment by Colk-tech** [comment]
(ごめんなさい)
![image](https://user-images.githubusercontent.com/53868423/114994790-1ce7a600-9ed8-11eb-9a2b-36138a6da409.png)

**Comment by siketyan** [comment]
草　じゃあ `root@siketyan.dev` に送り直してもろて

**Comment by siketyan** [comment]
@Colk-tech ping

**Comment by Colk-tech** [comment]
ごめん 出ていました
以降完了しましたわよ

**Comment by siketyan** [comment]
@Colk-tech せっかくだし DNSSEC 有効にしといて（レジストラ触れないのでまかせた

**Comment by siketyan** [comment]
https://canary.approvers.dev/ にデプロイしました，問題なければ approvers.dev も同様にしたいと思いますので LGTM ください

**Comment by siketyan** [comment]
ブログがバグってたんだった

**Comment by siketyan** [comment]
@Colk-tech ブログが正常にパッチされていない問題も解決したのでいつでも approvers.dev を Cloudflare Pages に移行できます．任意のタイミングで Go サインください

**Comment by Colk-tech** [comment]
Cloudflare に移行するのは構わないのですが、そうなると Google Domains のメール転送機能が使えなくなるので代替策を模索しています。

> @Colk-tech ブログが正常にパッチされていない問題も解決したのでいつでも approvers.dev を Cloudflare Pages に移行できます．任意のタイミングで Go サインください

**Comment by siketyan** [comment]
@Colk-tech ちょっと何を言っているのかわからないのですが， MX レコードには何も影響しません

**Comment by siketyan** [comment]
というか DNS 権威の移行はすでに済んでいますし， Pages の移行となんら関係ないはずです．

**Comment by Colk-tech** [comment]
まったくもってそのとおりでした。自分の無知ゆえにご迷惑をおかけして大変申し訳ないです。
この件に関しては承認とします。

**Comment by MikuroXina** [comment]
ステージングデプロイできているのに本番デプロイに失敗したので Reopen

**Comment by MikuroXina** [comment]
成功していました, 失敬.
