### ISSUE TITLE
[proposal] Changing the name of this repo

### ISSUE THREAD

**Issue by siketyan** [approvers/site#192]
Formerly, this repo is needed to be `approvers.github.io` because of the spec of GitHub Pages.
Now it is moved to Cloudflare Pages to host this app, so the naming is no longer needed.
I propose to change the name of this repo to `approvers.dev` or `site` or something much clear to understand.
Also I would appreciate if you could suggest the new name.

**Comment by MikuroXina** [comment]
`site` が打ちやすく便利でよいと思います.
