### ISSUE TITLE
GitHub Pagesへのデプロイを切る

### ISSUE THREAD

**Issue by m2en** [approvers/site#278]
![image](https://user-images.githubusercontent.com/82575685/201504365-98614bec-3428-4a83-9260-44fcb389d142.png)

Cf Pagesに移行したはずなのに定期的にGitHub Pagesへのデプロイが実行されているのでこれをOFFにしたい

**Comment by MikuroXina** [comment]
GitHub Pages の設定が間違っていたままでした. GitHub Pages のデプロイ設定を削除しておきました.
